### ISSUE TITLE
Option to render rather than precompile

### ISSUE THREAD

**Issue by PxlBuzzard** [sindresorhus/broccoli-nunjucks#1]
I run a website that serves static content. Precompiling doesn't really fit the bill here, I need to compile a nunjucks .html file back into html. I think adding an `options.type` and checking for `render`, `precompile` or if null assume `precompile` would work pretty well.

I don't think it would be too difficult to fit render into this project. I've written a [nunjucks renderer for Brunch](https://github.com/PxlBuzzard/nunjucks-brunch), so if you don't take up the task I might give it a shot.

**Comment by sindresorhus** [comment]
I'm open to a PR. How about explicit methods instead? `gulpNunjucks.precompile()` and `gulpNunjucks.render()` and have `gulpNunjucks()` be an alias for `gulpNunjucks.precompile()`.
